
name: CICD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secret.DOCKER_USERNAME }} -p ${{ secret.DOCKER_PASSWORD }} 
      - name: Build Docker Image
        run: docker build -t niravprajapati/aliens-app-typescript .
      - name: Publish Image to Docker Hub
        run: docker push niravprajapati/aliens-app-typescript:latest

  deploy:
    needs: build
    runs-on: aws-ec2
